[package]
name = "garr"
version = "0.0.1"
authors = ["wang-q <wang-q@outlook.com>"]
edition = "2018"
description = "Genome Analyst with Rust and Redis"
documentation = "https://github.com/wang-q/garr"
readme = "README.md"
homepage = "https://github.com/wang-q/garr"
repository = "https://github.com/wang-q/garr"
license = "MIT"
categories = ["command-line-utilities", "bioinformatics"]
publish = false

[[bin]]
name = "garr"
path = "src/garr.rs"

[dependencies]
clap = "2"
regex = "1"
lazy_static = "1.3.0"
flate2 = "1.0"
tera = "1"
intspan = "0.4.14"
itertools = "0.9.0"
redis = { version = "0.20.0", features = ["tls"] }
rand = "0.8.1"
serde = "1.0"
envy = "0.4"
dotenv = "0.15.0"

[build-dependencies]

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11"
predicates = "1"

[profile.release]
lto = true
