[package]
name = "gars"
version = "0.1.1-alpha.0"
authors = ["wang-q <wang-q@outlook.com>"]
edition = "2018"
description = "Genome Analyst with Rust and rediS"
documentation = "https://github.com/wang-q/gars"
readme = "README.md"
homepage = "https://github.com/wang-q/gars"
repository = "https://github.com/wang-q/gars"
license = "MIT"
categories = ["command-line-utilities", "science"]
publish = false

[[bin]]
name = "gars"
path = "src/gars.rs"

[dependencies]
clap = { version = "3.1.1", features = ["derive", "cargo"] }
lazy_static = "1.3.0"
tera = "1"
intspan = "0.4.15"
redis = { version = "0.20.0", features = ["tls"] }
rand = "0.8.1"
serde = "1.0"
envy = "0.4"
dotenv = "0.15.0"
bio = "0.30.0"
#polars = { version = "0.20.0", features = ["dtype-slim"] }

[build-dependencies]

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11"
predicates = "1"
approx = "0.5.0"

[profile.release]
lto = true
