[package]
name = "gars"
version = "0.3.1"
authors = ["wang-q <wang-q@outlook.com>"]
edition = "2018"
description = "Genome Analyst with Rust and rediS"
documentation = "https://github.com/wang-q/gars"
readme = "README.md"
homepage = "https://github.com/wang-q/gars"
repository = "https://github.com/wang-q/gars"
license = "MIT"
categories = ["command-line-utilities", "science"]
publish = false

[dependencies]
clap = { version = "3.2.2", features = ["cargo"] }
regex = "1.5.6"
lazy_static = "1.3.0"
tera = "1.16.0"

redis = { version = "0.21.5", default-features = false, features = ["script"] }
flate2 = "1.0.24"
rand = "0.8.1"
serde = "1.0.137"
envy = "0.4.2"
dotenv = "0.15.0"

#log = "0.4"
#simplelog = "^0.10.0"

intspan = "0.7.1"
bio = "0.30.0"

# serialize
rust-lapper = { version = "1.0.1", features = ["with_serde"] }
bincode = "1.3.3"

polars = { version = "0.20.0", optional = true, features = ["dtype-slim"] }

[features]
build-stat = ["polars"]

[[bin]]
name = "gars"
path = "src/gars.rs"

[[bin]]
name = "gars-stat"
path = "src/gars-stat.rs"
required-features = ["build-stat"]

[build-dependencies]

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11"
predicates = "1"
approx = "0.5.0"

[profile.release]
lto = true
