name: Code Coverage

on: [push]

env:
  CARGO_TERM_COLOR: always
  REDIS_VERSION: '6.2.4'

jobs:
  check:
    name: codecov gams
    runs-on: ubuntu-latest
    steps:
      - name: Cache redis
        id: cache-redis
        uses: actions/cache@v2
        with:
          path: |
            /usr/bin/redis-cli
            /usr/bin/redis-server
          key: ${{ runner.os }}-redis

      - name: Install redis
        if: steps.cache-redis.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install stunnel -y
          wget https://github.com/redis/redis/archive/${{ env.REDIS_VERSION }}.tar.gz;
          tar -xzvf ${{ env.REDIS_VERSION }}.tar.gz;
          pushd redis-${{ env.REDIS_VERSION }} && BUILD_TLS=yes make && sudo mv src/redis-server src/redis-cli /usr/bin/ && popd;
          echo $PATH

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: redis
        run: redis-server --appendonly no --dir tests/S288c/ &

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'
          args: ' --bins --tests --follow-exec -- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
