name: Code Coverage

on: [push]

env:
  CARGO_TERM_COLOR: always
  REDIS_VERSION: '6.2.4'

jobs:
  check:
    name: codecov gams
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "5.x"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --bins --tests --follow-exec --engine llvm --out xml -- --test-threads 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true
