name: Code Coverage

on: [push]

env:
  CARGO_TERM_COLOR: always
  REDIS_VERSION: '6.2.4'

jobs:
  check:
    name: codecov gams
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Cache redis
        id: cache-redis
        uses: actions/cache@v2
        with:
          path: |
            /usr/bin/redis-cli
            /usr/bin/redis-server
          key: ${{ runner.os }}-redis

      - name: Install redis
        if: steps.cache-redis.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install stunnel -y
          wget https://github.com/redis/redis/archive/${{ env.REDIS_VERSION }}.tar.gz;
          tar -xzvf ${{ env.REDIS_VERSION }}.tar.gz;
          pushd redis-${{ env.REDIS_VERSION }} && BUILD_TLS=yes make && sudo mv src/redis-server src/redis-cli /usr/bin/ && popd;
          echo $PATH

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: redis
        run: redis-server --appendonly no --dir tests/S288c/ &

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --bins --tests --follow-exec --engine llvm --out xml -- --test-threads 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
